-- 000011_identity_uniqueness.up.sql
-- Argus Phase 2 (M7-S3 remediation, P2-AC-01/02) — DB-enforced identity
-- uniqueness for OPEN identity windows.
--
-- Canonical semantics (docs/07 §11.4): identity keys (serial, chassis ID,
-- sysObjectID, MAC, hostname, mgmt IP) identify one live device; duplicates
-- become merge-review items instead of silent double-inventory. The identity
-- history is a windowed (SCD-2) table (docs/11 §21.1: first_seen_at /
-- last_seen_at, NULL = open), so uniqueness applies ONLY to open windows:
-- exactly one live device per (org, identifier_type, identifier_value).
-- Closed (historical) rows may repeat — device replacement and IP/DHCP reuse
-- legitimately reopen a value on another device once the old window is closed.
--
-- The existing lookup index device_identity_history_org_ident is kept (it
-- still serves "who had this identity over time" queries).
--
-- Upgrade note: a database that already contains duplicate OPEN windows fails
-- this migration loudly (unique index build). M7-S1/S2 data was generated by
-- the API, which (after this remediation) cannot create duplicates; any
-- pre-existing duplicates must be reconciled by closing the stale window
-- before applying.

CREATE UNIQUE INDEX device_identity_history_open_uniq
    ON device_identity_history (org_id, identifier_type, identifier_value)
    WHERE last_seen_at IS NULL;
