#!/bin/sh
# scripts/db-init/01-roles.sh
# DEV-ONLY bootstrap executed by the TimescaleDB container on first
# initialization (/docker-entrypoint-initdb.d). It converges the base role
# attributes to exactly what migrations/000005_rls.up.sql expects and creates
# the dev LOGIN roles whose password comes from ARGUS_DEV_DB_PASSWORD
# (compose passes it from deployments/compose/.env, generated by
# scripts/dev.ps1; a bare `docker compose up` falls back to a local
# placeholder). NEVER use this file in production.
#
# The SQL below is a single source of truth: the integration harness extracts
# the same heredoc and applies it against the testcontainers database.
set -eu

: "${ARGUS_DEV_DB_PASSWORD:=dev-db-change-me}"

psql -v ON_ERROR_STOP=1 -v pw="$ARGUS_DEV_DB_PASSWORD" \
     --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'argus_app') THEN
        CREATE ROLE argus_app;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'argus_auth') THEN
        CREATE ROLE argus_auth;
    END IF;
END
$$;

-- Converge attributes regardless of prior state.
ALTER ROLE argus_app  NOLOGIN NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER ROLE argus_auth NOLOGIN BYPASSRLS  NOSUPERUSER NOCREATEDB NOCREATEROLE;

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'argus_app_login') THEN
        CREATE ROLE argus_app_login LOGIN;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'argus_auth_login') THEN
        CREATE ROLE argus_auth_login LOGIN;
    END IF;
END
$$;

ALTER ROLE argus_app_login  PASSWORD :'pw';
ALTER ROLE argus_auth_login PASSWORD :'pw';

GRANT argus_app  TO argus_app_login;
GRANT argus_auth TO argus_auth_login;
SQL
