import { defineConfig } from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

// Load dev credentials generated by scripts/dev.ps1 (gitignored .env) so the
// specs can log in without exporting variables by hand; the documented
// placeholders apply when no .env file exists.
try {
  const envFile = resolve(process.cwd(), "..", "deployments", "compose", ".env");
  for (const line of readFileSync(envFile, "utf8").split(/\r?\n/)) {
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line.trim());
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2];
    }
  }
} catch {
  /* no .env: placeholders apply */
}

// Runs against a locally started web app (npm run build && npm run start)
// with the dev compose stack (API on :8080) running.
export default defineConfig({
  testDir: "./e2e",
  timeout: 30_000,
  retries: 0,
  reporter: "list",
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? "http://127.0.0.1:3000",
  },
});
